inherit_from: .rubocop_todo.yml

# Allow compact style in the tests.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

# Don't require doc comments in general.
Style/Documentation:
  Enabled: false

# Allow complex methods
Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'lib/aoc2019/sunny_asteroids.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/aoc2019/sunny_asteroids.rb'

Metrics/CyclomaticComplexity:
  Max: 20
  Exclude:
    - 'lib/aoc2019/sunny_asteroids.rb'

Metrics/PerceivedComplexity:
  Max: 20
  Exclude:
    - 'lib/aoc2019/sunny_asteroids.rb'

# Allow long methods
Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'test/**/*'
    - 'lib/aoc2019/sunny_asteroids.rb'

# Allow short param names.
Naming/UncommunicativeMethodParamName:
  Enabled: false

# Allow chaining blocks for solution efficiency.
Style/MultilineBlockChain:
  Enabled: false

# Turn this nonsense off.
Style/WordArray:
  EnforcedStyle: brackets
